### ISSUE TITLE
Poll etl task - job poll retry delay

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-php-client#5]
Dostal jsem dotaz na pomalé chování gd writeru https://keboola.zendesk.com/agent/tickets/9617

Nemyslím si že to bude dané tím ale co mě  zarazilo že je že interval čekání na další test jobu pořád roste s dobou zpracování https://github.com/keboola/gooddata-php-client/blob/5de5bfed7cba014496f108d4065d23ccd2c0c5b0/src/Keboola/GoodData/Datasets.php#L103

Je to nějaký požadavek Gooddata? Jinak by se tomu max doba čekání mohla omezit např. na 20sec podobně jako to máme u sapi klienta https://github.com/keboola/storage-api-php-client/blob/5ddb2e65815f74e53c2a79489fb94d6e466ef4da/src/Keboola/StorageApi/createSimpleJobPollDelay.php#L9

U delších jobů by to mohlo nějaký čas ušetřit.

**Comment by JakubMatejka** [comment]
Hm, to bude historicky. Typicky to u velkých datasetů trvá (trvalo) dost dlouho, tak to bylo takhle nastavený. Určitě bych to čekání nestropoval, ale to čekání by mohlo být aspoň konstatntní.

**Comment by JakubMatejka** [comment]
Aha, jasně. Dal jsem tam 10-20, ať to není úplně konstatntní (Kratší interval jako u toho SAPI klienta ani IMHO nemá smysl): https://github.com/keboola/gooddata-php-client/pull/6/files

**Comment by JakubMatejka** [comment]
Akorát Travis nějak nestartuje 🤔
